# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'FirstProjects' do
  pod 'YYKit', '~> 1.0.9'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'Masonry', '~> 1.0.2'
  pod 'AFNetworking', '~> 3.1.0'

end
